module.exports = [
    {
        id: 1,
        cardId: 1,
        img: '1-2.png',
        clr: 'black',
        pos: 1,
    },
    {
        id: 2,
        cardId: 1,
        img: '1-3.png',
        clr: 'black',
        pos: 2,
    },
    {
        id: 3,
        cardId: 1,
        img: '1-4.png',
        clr: 'black',
        pos: 3,
    },
    {
        id: 4,
        cardId: 1,
        img: '1-5.png',
        clr: 'black',
        pos: 4,
    },
    {
        id: 5,
        cardId: 1,
        img: '1-6.png',
        clr: 'black',
        pos: 5,
    },
    {
        id: 6,
        cardId: 1,
        img: '1-7.png',
        clr: 'black',
        pos: 6,
    },
    {
        id: 7,
        cardId: 1,
        img: '1-8.png',
        clr: 'black',
        pos: 7,
    },
    {
        id: 8,
        cardId: 1,
        img: '1-9.png',
        clr: 'black',
        pos: 8,
    },
    {
        id: 9,
        cardId: 1,
        img: '1-10.png',
        clr: 'black',
        pos: 9,
    },
    {
        id: 10,
        cardId: 1,
        img: '1-j.png',
        clr: 'black',
        pos: 10,
    },
    {
        id: 11,
        cardId: 1,
        img: '1-q.png',
        clr: 'black',
        pos: 11,
    },
    {
        id: 12,
        cardId: 1,
        img: '1-k.png',
        clr: 'black',
        pos: 12,
    },
    {
        id: 13,
        cardId: 1,
        img: '1-t.png',
        clr: 'black',
        pos: 13,
    },
    
    {
        id: 14,
        cardId: 2,
        img: '2-2.png',
        clr: 'black',
        pos: 1,
    },
    {
        id: 15,
        cardId: 2,
        img: '2-3.png',
        clr: 'black',
        pos: 2,
    },
    {
        id: 16,
        cardId: 2,
        img: '2-4.png',
        clr: 'black',
        pos: 3,
    },
    {
        id: 17,
        cardId: 2,
        img: '2-5.png',
        clr: 'black',
        pos: 4,
    },
    {
        id: 18,
        cardId: 2,
        img: '2-6.png',
        clr: 'black',
        pos: 5,
    },
    {
        id: 19,
        cardId: 2,
        img: '2-7.png',
        clr: 'black',
        pos: 6,
    },
    {
        id: 20,
        cardId: 2,
        img: '2-8.png',
        clr: 'black',
        pos: 7,
    },
    {
        id: 21,
        cardId: 2,
        img: '2-9.png',
        clr: 'black',
        pos: 8,
    },
    {
        id: 22,
        cardId: 2,
        img: '2-10.png',
        clr: 'black',
        pos: 9,
    },
    {
        id: 23,
        cardId: 2,
        img: '2-j.png',
        clr: 'black',
        pos: 10,
    },
    {
        id: 24,
        cardId: 2,
        img: '2-q.png',
        clr: 'black',
        pos: 11,
    },
    {
        id: 25,
        cardId: 2,
        img: '2-k.png',
        clr: 'black',
        pos: 12,
    },
    {
        id: 26,
        cardId: 2,
        img: '2-t.png',
        clr: 'black',
        pos: 13,
    },

    {
        id: 27,
        cardId: 3,
        img: '3-2.png',
        clr: 'red',
        pos: 1,
    },
    {
        id: 28,
        cardId: 3,
        img: '3-3.png',
        clr: 'red',
        pos: 2,
    },
    {
        id: 29,
        cardId: 3,
        img: '3-4.png',
        clr: 'red',
        pos: 3,
    },
    {
        id: 30,
        cardId: 3,
        img: '3-5.png',
        clr: 'red',
        pos: 4,
    },
    {
        id: 31,
        cardId: 3,
        img: '3-6.png',
        clr: 'red',
        pos: 5,
    },
    {
        id: 32,
        cardId: 3,
        img: '3-7.png',
        clr: 'red',
        pos: 6,
    },
    {
        id: 33,
        cardId: 3,
        img: '3-8.png',
        clr: 'red',
        pos: 7,
    },
    {
        id: 34,
        cardId: 3,
        img: '3-9.png',
        clr: 'red',
        pos: 8,
    },
    {
        id: 35,
        cardId: 3,
        img: '3-10.png',
        clr: 'red',
        pos: 9,
    },
    {
        id: 36,
        cardId: 3,
        img: '3-j.png',
        clr: 'red',
        pos: 10,
    },
    {
        id: 37,
        cardId: 3,
        img: '3-q.png',
        clr: 'red',
        pos: 11,
    },
    {
        id: 38,
        cardId: 3,
        img: '3-k.png',
        clr: 'red',
        pos: 12,
    },
    {
        id: 39,
        cardId: 3,
        img: '3-t.png',
        clr: 'red',
        pos: 13,
    },

    {
        id: 40,
        cardId: 4,
        img: '4-2.png',
        clr: 'red',
        pos: 1,
    },
    {
        id: 41,
        cardId: 4,
        img: '4-3.png',
        clr: 'red',
        pos: 2,
    },
    {
        id: 42,
        cardId: 4,
        img: '4-4.png',
        clr: 'red',
        pos: 3,
    },
    {
        id: 43,
        cardId: 4,
        img: '4-5.png',
        clr: 'red',
        pos: 4,
    },
    {
        id: 44,
        cardId: 4,
        img: '4-6.png',
        clr: 'red',
        pos: 5,
    },
    {
        id: 45,
        cardId: 4,
        img: '4-7.png',
        clr: 'red',
        pos: 6,
    },
    {
        id: 46,
        cardId: 4,
        img: '4-8.png',
        clr: 'red',
        pos: 7,
    },
    {
        id: 47,
        cardId: 4,
        img: '4-9.png',
        clr: 'red',
        pos: 8,
    },
    {
        id: 48,
        cardId: 4,
        img: '4-10.png',
        clr: 'red',
        pos: 9,
    },
    {
        id: 49,
        cardId: 4,
        img: '4-j.png',
        clr: 'red',
        pos: 10,
    },
    {
        id: 50,
        cardId: 4,
        img: '4-q.png',
        clr: 'red',
        pos: 11,
    },
    {
        id: 51,
        cardId: 4,
        img: '4-k.png',
        clr: 'red',
        pos: 12,
    },
    {
        id: 52,
        cardId: 4,
        img: '4-t.png',
        clr: 'red',
        pos: 13,
    },
]